# Generated by Django 3.2.12 on 2022-09-27 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0003_alter_paint_options_alter_year_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paints.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img/photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
