# Generated by Django 3.2.12 on 2022-09-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0004_auto_20220927_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/img/photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
