# Generated by Django 4.1.1 on 2022-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0005_alter_paint_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='author_repeat',
            field=models.BooleanField(default=False, verbose_name='Авторский повтор'),
        ),
    ]
