# Generated by Django 4.1.1 on 2022-10-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0006_paint_author_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ориентация')),
            ],
            options={
                'verbose_name': 'Ориентация ',
                'verbose_name_plural': 'Ориентация',
            },
        ),
        migrations.AddField(
            model_name='paint',
            name='orientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paints.orientation', verbose_name='Ориентация'),
        ),
    ]
