# Generated by Django 4.1.3 on 2022-11-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0007_orientation_paint_orientation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orientation',
            options={'verbose_name': 'Ориентация', 'verbose_name_plural': 'Ориентация'},
        ),
    ]
