# Generated by Django 4.1.3 on 2022-11-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0008_alter_orientation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paints.paint', verbose_name='Картина')),
            ],
        ),
    ]
